# Generated by Django 5.2 on 2025-04-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('TRANSFER BANCAR', 'Transfer Bancar'), ('NUMERAR', 'Numerar'), ('N/A', 'N/A')], default='TRANSFER BANCAR', max_length=20),
        ),
    ]
