# Generated by Django 5.2 on 2025-04-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='suspension_of_duplication',
            field=models.BooleanField(default=False, help_text='If True, duplicate transaction checks will be ignored'),
        ),
    ]
